import Head from "next/head";
import { LoggedOutNavBar } from "@component/navbar/logged-out/LoggedOutNavBar";
import { Footer } from "@component/navbar/footer/footer";

interface DefaultLayoutProps {
  showNavbar?: boolean;
  showFooter?: boolean;
  children: JSX.Element;
}

export const Route = {
  DASHBOARD: {
    PARENT: "/dashboard",
    SETTINGS: "/dashboard/settings",
    PLANS: "/dashboard/plans",
  },
  PRICING: "/pricing",
  SIGNUP: "/sign-up",
  LOGIN: "/auth/signin",
  FEATURES: "/features",
  FAQ: "/faq",
  ROOT: "/",
};

export function DefaultLayout({
  children,
  showNavbar = true,
  showFooter = true,
}: DefaultLayoutProps) {
  return (
    <>
      <Head>
        <title>Template Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showNavbar ? <LoggedOutNavBar /> : null}
      <main className="flex min-h-screen flex-col items-center justify-center">
        {children}
      </main>
      {showFooter ? <Footer /> : null}
    </>
  );
}
