import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { LoggedOutNavBar } from "@component/navbar/logged-out/LoggedOutNavBar";
import { Footer } from "@component/navbar/footer/footer";
import { Login } from "@component/authentication/Login";

interface DefaultLayoutProps {
  showNavbar?: boolean;
  showFooter?: boolean;
  children: JSX.Element;
}

export const Route = {
  DASHBOARD: {
    PARENT: "/dashboard",
    OVERVIEW: "/dashboard/overview",
    SETTINGS: "/dashboard/settings",
  },
  PRICING: "/pricing",
  SIGNUP: "/sign-up",
  LOGIN: "/login",
  FEATURES: "/features",
  FAQ: "/faq",
  ROOT: "/",
};

export function DefaultLayout({
  children,
  showNavbar = true,
  showFooter = true,
}: DefaultLayoutProps) {
  const { data: session } = useSession();
  const router = useRouter();
  const currentUrl = router.asPath;

  // TODO Add loading spinner
  // TODO Research route guards
  if (
    (!session && currentUrl === Route.DASHBOARD.PARENT) ||
    currentUrl === Route.ROOT
  ) {
    return <Login />;
  }

  return (
    <>
      <Head>
        <title>Template Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showNavbar ? <LoggedOutNavBar /> : null}
      <main className="flex min-h-screen flex-col items-center justify-center">
        {children}
      </main>
      {showFooter ? <Footer /> : null}
    </>
  );
}
